service:
  pdns:
    image: bosdaring/pdns-admin:latest
    container_name: pdns
    restart: unless-stopped
    volumes:
      - ./pdns:/data
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8080:80/tcp #powerdns-admin interface
      - 8081:8081/tcp #optional expose pdns API 
    environment:
      - USER=pdns
      - SECRET_KEY='changeme'
